export interface Product {
  id: string
  name: string
  category: string
  price: number
  originalPrice?: number
  rating: number
  reviewCount: number
  description: string
  image: string
  inStock: boolean
  badge?: string
}

export const CATEGORIES = [
  'All',
  'Smartwatches',
  'Headphones',
  'Cameras',
  'Speakers',
  'Accessories',
]

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Elite Pro Smartwatch',
    category: 'Smartwatches',
    price: 599,
    originalPrice: 699,
    rating: 4.8,
    reviewCount: 342,
    description: 'Advanced health tracking with 7-day battery life and premium titanium build.',
    image: '⌚',
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: '2',
    name: 'Quantum Audio Pro',
    category: 'Headphones',
    price: 349,
    originalPrice: 449,
    rating: 4.7,
    reviewCount: 521,
    description: 'Noise-cancelling headphones with 40-hour battery and premium sound quality.',
    image: '🎧',
    inStock: true,
    badge: 'Popular',
  },
  {
    id: '3',
    name: 'Crystal Lens Camera',
    category: 'Cameras',
    price: 1299,
    rating: 4.9,
    reviewCount: 189,
    description: '4K mirrorless camera with advanced stabilization and AI autofocus.',
    image: '📷',
    inStock: true,
    badge: 'New',
  },
  {
    id: '4',
    name: 'Sonic Boom Speaker',
    category: 'Speakers',
    price: 249,
    originalPrice: 299,
    rating: 4.6,
    reviewCount: 276,
    description: 'Portable premium speaker with 360° sound and 12-hour battery.',
    image: '🔊',
    inStock: true,
  },
  {
    id: '5',
    name: 'Swift Charger Pro',
    category: 'Accessories',
    price: 79,
    originalPrice: 99,
    rating: 4.8,
    reviewCount: 612,
    description: 'Ultra-fast 120W charging with multiple device support.',
    image: '🔌',
    inStock: true,
  },
  {
    id: '6',
    name: 'Apex Wireless Buds',
    category: 'Headphones',
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviewCount: 445,
    description: 'True wireless earbuds with adaptive noise cancellation.',
    image: '🎵',
    inStock: true,
    badge: 'Popular',
  },
  {
    id: '7',
    name: 'Pro Monitor Display',
    category: 'Accessories',
    price: 599,
    rating: 4.8,
    reviewCount: 178,
    description: '32" 4K monitor with HDR and 144Hz refresh rate.',
    image: '🖥️',
    inStock: true,
  },
  {
    id: '8',
    name: 'Vision VR Headset',
    category: 'Accessories',
    price: 799,
    rating: 4.6,
    reviewCount: 234,
    description: 'Immersive VR experience with 120° field of view.',
    image: '🥽',
    inStock: true,
    badge: 'New',
  },
  {
    id: '9',
    name: 'TimeKeep Classic',
    category: 'Smartwatches',
    price: 299,
    originalPrice: 349,
    rating: 4.5,
    reviewCount: 267,
    description: 'Elegant analog smartwatch with fitness tracking.',
    image: '⌚',
    inStock: true,
  },
  {
    id: '10',
    name: 'Echo Studio Speaker',
    category: 'Speakers',
    price: 449,
    rating: 4.7,
    reviewCount: 398,
    description: 'Premium smart speaker with immersive surround sound.',
    image: '🔊',
    inStock: true,
  },
  {
    id: '11',
    name: 'Swift Power Bank',
    category: 'Accessories',
    price: 89,
    originalPrice: 119,
    rating: 4.6,
    reviewCount: 523,
    description: '50000mAh power bank with 65W fast charging.',
    image: '🔋',
    inStock: true,
  },
  {
    id: '12',
    name: 'Prisma RGB Keyboard',
    category: 'Accessories',
    price: 159,
    originalPrice: 199,
    rating: 4.5,
    reviewCount: 342,
    description: 'Mechanical gaming keyboard with customizable RGB lighting.',
    image: '⌨️',
    inStock: true,
  },
  {
    id: '13',
    name: 'Summit Trail Earbuds',
    category: 'Headphones',
    price: 129,
    rating: 4.4,
    reviewCount: 289,
    description: 'Waterproof sports earbuds with secure fit design.',
    image: '🎧',
    inStock: true,
  },
  {
    id: '14',
    name: 'Lens Capture 360',
    category: 'Cameras',
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviewCount: 201,
    description: '360-degree action camera perfect for adventure enthusiasts.',
    image: '📹',
    inStock: true,
  },
  {
    id: '15',
    name: 'GripMaster Pro Mouse',
    category: 'Accessories',
    price: 99,
    rating: 4.7,
    reviewCount: 467,
    description: 'Precision gaming mouse with programmable buttons.',
    image: '🖱️',
    inStock: true,
  },
  {
    id: '16',
    name: 'Tempo Sport Watch',
    category: 'Smartwatches',
    price: 249,
    rating: 4.5,
    reviewCount: 298,
    description: 'Lightweight sports smartwatch with advanced metrics.',
    image: '⌚',
    inStock: true,
  },
  {
    id: '17',
    name: 'Zen Meditation Pod',
    category: 'Speakers',
    price: 179,
    originalPrice: 229,
    rating: 4.6,
    reviewCount: 156,
    description: 'Portable speaker designed for meditation and relaxation.',
    image: '🔊',
    inStock: true,
  },
  {
    id: '18',
    name: 'Studio Pro Microphone',
    category: 'Accessories',
    price: 279,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 312,
    description: 'Professional-grade USB microphone for content creators.',
    image: '🎤',
    inStock: true,
  },
  {
    id: '19',
    name: 'Fiber Optic Cable Kit',
    category: 'Accessories',
    price: 49,
    rating: 4.5,
    reviewCount: 234,
    description: 'Premium cables with enhanced durability and conductivity.',
    image: '🔌',
    inStock: true,
  },
  {
    id: '20',
    name: 'Nexus 8K Projector',
    category: 'Cameras',
    price: 2499,
    rating: 4.9,
    reviewCount: 87,
    description: '8K resolution projector for home theater setup.',
    image: '🎬',
    inStock: false,
    badge: 'Coming Soon',
  },
]
